# Generated by Django 5.0.2 on 2024-02-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
