# Generated by Django 5.0.2 on 2024-02-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_company_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('yf_total_esg_score', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='yf_total_esg_score',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
    ]
