# Generated by Django 5.0.2 on 2024-02-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_etf_company_yf_total_esg_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='etf',
            name='yf_e_score',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etf',
            name='yf_g_score',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etf',
            name='yf_s_score',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
    ]
