# Generated by Django 5.0.2 on 2024-03-04 00:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0007_rename_yf_total_esg_score_company_yf_e_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="etf",
            old_name="yf_e_score",
            new_name="vf_esg_score",
        ),
        migrations.RemoveField(
            model_name="etf",
            name="yf_g_score",
        ),
        migrations.RemoveField(
            model_name="etf",
            name="yf_s_score",
        ),
        migrations.RemoveField(
            model_name="etf",
            name="yf_t_score",
        ),
    ]
