# Generated by Django 5.0.2 on 2024-03-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_yf_e_score_etf_vf_esg_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DumbUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('portfolio', models.JSONField()),
            ],
        ),
    ]
